apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 4
  revisionHistoryLimit: 0   # delete old ReplicaSets immediately
  selector:
    matchLabels:
      app: wisecow
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:ab4125e37508e7af07c35253019f9dd217e0d0d4
        ports:
        - containerPort: 4499
        
