apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
  namespace: wisecow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:latest
        ports:
        - containerPort: 4499
        readinessProbe:
          tcpSocket:
            port: 4499
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 4499
          initialDelaySeconds: 20
          periodSeconds: 20
