apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 4
  revisionHistoryLimit: 0   # delete old ReplicaSets immediately
  selector:
    matchLabels:
      app: wisecow
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:4d62e3143e37685eb030b7a0d9faac203e0142c8
        ports:
        - containerPort: 4499
