apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:1c4a635247a83b6cf71fc9bb4d4110bf7ce939ca
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499