apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:62a7d3c556e221120c08116f8a55b727451aeee8
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499