apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:a4f9caacba6085df7bb44eb0a3bcd48886a7006d
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499