apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:cfc2478afe33551b2c9997eaff9d01166ff4a641
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499