apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:b8f92d788ff6189ca48c005db8ae9ed631dfcc4f
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499