apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:8ae58777793c21051c60bc7819a5df74ec73e574
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499