apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:ceab7928f6af2485daae9cdc3b369b10bb0f6758
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499