apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:89e1c438bb621c7e6e0ffe6c8d165176f45579dc
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499