apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:313c3af7a10e420eee95686e67593e72b4bd3144
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499