apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:6ee710c99527a314ba94cd3bd9954d0a1d868aac
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499