apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:fc3c1dc019bb052f90c76ad23ecb516305085e2d
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499