apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:33989df820f2209ddd34294157253f9f255ea0ae
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499