apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:fe51bbefaee5f54aa5fdf1f6e96d5eea73605835
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499