apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:3f4b99bb45baa1aac46780faeb15d337960bc83f
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499