apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:b2a2a5af69eb5925c236c77eb0e925b7c995d716
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499