apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:0a182bbcbb40b926f9dc3369b461e9df26902be4
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499