apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:5c83745f97af7f7e4fa64ac4ab490d08ba98e420
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499