apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:57c1eab47ee2628864a080eb68722fb820b9b890
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499