apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:6788d1514e037dc0f76252859c114bd4da00db07
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499