apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:97c26ea17d3e1dd8f141f6ccf45a0c3d59a0462d
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499