apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:831326d1cd27455fcb5c37f95e5fbf152b5dff28
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499