apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harishasapu/wisecow:32cf744bdd44561c92ae1b232ab2dfdf6ec3f185
        imagePullPolicy: Never   # <- Add this line
        ports:
        - containerPort: 4499