apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wisecow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/harishasapu/accuknox-submission.git
    targetRevision: main
    path: k8s/
  destination:
    server: https://kubernetes.default.svc
    namespace: wisecow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
