apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wisecow-app
  namespace: argocd
  annotations:
    # 🚀 Argo CD Image Updater Configuration
    # The image to track and automatically update
    argocd-image-updater.argoproj.io/image-list: wisecow=harishasapu/wisecow
    # Update strategy — always use the newest image pushed
    argocd-image-updater.argoproj.io/wisecow.update-strategy: newest-build
    # Write updated image tags back to Git (so ArgoCD can sync)
    argocd-image-updater.argoproj.io/write-back-method: git
    # Branch to update in your Git repo
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default

  source:
    repoURL: 'https://github.com/harishasapu/accuknox-submission.git'
    targetRevision: main
    path: k8s  # adjust if your manifests live in "gitops" instead

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true           # remove old Kubernetes objects not defined in Git
      selfHeal: true        # auto-correct drift
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true           # create target namespace if missing
      - PrunePropagationPolicy=Foreground  # delete old ReplicaSets & Pods before new rollout
      - PruneLast=true                 # ensure pruning happens after sync
      - ApplyOutOfSyncOnly=true             # only apply when something changed
      - Replace=true                        # replace instead of patch to remove old pods cleanly











# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: wisecow-app
#   namespace: argocd
# spec:
#   project: default

#   source:
#     repoURL: 'https://github.com/harishasapu/accuknox-submission.git'
#     targetRevision: main
#     path: k8s

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - Replace=true                     # 🔁 Force delete old pods & recreate
#       - PrunePropagationPolicy=foreground
#       - PruneLast=true
#       - ApplyOutOfSyncOnly=true


# # ---
# # apiVersion: argoproj.io/v1alpha1
# # kind: Application
# # metadata:
# #   name: wisecow-app
# #   namespace: argocd
# #   annotations:
# #     # 👇 Argo CD Image Updater configuration
# #     argocd-image-updater.argoproj.io/image-list: wisecow=harishasapu/wisecow:latest
# #     argocd-image-updater.argoproj.io/wisecow.update-strategy: latest
# #     argocd-image-updater.argoproj.io/write-back-method: git
# #     argocd-image-updater.argoproj.io/git-branch: main
# # spec:
# #   project: default

# #   source:
# #     repoURL: 'https://github.com/harishasapu/accuknox-submission.git'
# #     targetRevision: main
# #     path: k8s

# #   destination:
# #     server: https://kubernetes.default.svc
# #     namespace: default

# #   syncPolicy:
# #     automated:
# #       prune: true           # remove old objects not in Git
# #       selfHeal: true        # fix drift automatically
# #     syncOptions:
# #       - CreateNamespace=true
# #       - PrunePropagationPolicy=foreground
# #       - PruneLast=true

# # ---

# # apiVersion: argoproj.io/v1alpha1
# # kind: Application
# # metadata:
# #   name: wisecow-app
# #   namespace: argocd
# #   annotations:
# #     # 👇 Argo CD Image Updater configuration
# #     # Replace "harishasapu" with your actual Docker Hub username if different
# #     argocd-image-updater.argoproj.io/image-list: wisecow=${DOCKER_USERNAME:-harishasapu}/wisecow:latest
# #     argocd-image-updater.argoproj.io/wisecow.update-strategy: latest
# #     argocd-image-updater.argoproj.io/write-back-method: git
# #     argocd-image-updater.argoproj.io/git-branch: main
# #     argocd-image-updater.argoproj.io/wisecow.allow-tags: regexp:^([a-f0-9]{7,40}|latest)$
# # spec:
# #   project: default

# #   source:
# #     repoURL: 'https://github.com/harishasapu/accuknox-submission.git'
# #     targetRevision: main
# #     path: k8s

# #   destination:
# #     server: https://kubernetes.default.svc
# #     namespace: default

# #   syncPolicy:
# #     automated:
# #       prune: true
# #       selfHeal: true
# #     syncOptions:
# #       - CreateNamespace=true
# #       - PrunePropagationPolicy=foreground
# #       - PruneLast=true

