apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wisecow-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/harishasapu/accuknox-submission.git'
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true                     # 🔁 Force delete old pods & recreate
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
