name: CI/CD — Build, Push, Deploy (Wisecow)

on:
  push:
    branches: [ main ]

env:
  IMAGE: ${{ secrets.IMAGE_NAME }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image_tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Determine Image Tag
      id: set-tag
      run: echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Build and Push Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.IMAGE_NAME }}:${{ steps.set-tag.outputs.image_tag }}
          ${{ secrets.IMAGE_NAME }}:latest

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    if: ${{ secrets.KUBE_CONFIG != '' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3

    - name: Decode kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
        chmod 600 kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    - name: Replace Image Placeholder
      run: |
        IMAGE=${{ secrets.IMAGE_NAME }}:${{ needs.build-push.outputs.image-tag }}
        sed -i "s|${IMAGE_PLACEHOLDER}|${IMAGE}|g" k8s/deployment.yaml

    - name: Deploy to Cluster
      run: |
        export KUBECONFIG=$(pwd)/kubeconfig
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/cluster-issuer.yaml || true
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
