name: Wisecow CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}   # Use your Personal Access Token for push permissions

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/wisecow:latest
          ${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.sha }}

    - name: Update image in wisecow-deployment.yaml
      run: |
        sed -i "s|image: .*/wisecow:.*|image: ${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.sha }}|" k8s/wisecow-deployment.yaml

    - name: Commit and push updated deployment.yaml
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update image tag in wisecow-deployment.yaml"
        file_pattern: k8s/wisecow-deployment.yaml
